### ISSUE TITLE
How you can enter the End Portal in PMMP?

### ISSUE THREAD

**Issue by TheBalkanDev** [OguzhanUmutlu/Manhunt#1]
There are no structures implemented yet.

**Comment by OguzhanUmutlu** [comment]
So they should use a portal plugin and a dragon plugin.

**Comment by TheBalkanDev** [comment]
Plugins like this don’t exist

**Comment by ZZWILLIAMXXTrue** [comment]
I was too thinking about this. Its only possible if you download a vanilla worlds and use vanilla enhancement plugins
